# Generated by Django 4.2.2 on 2023-07-08 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("card_number", models.CharField(max_length=16)),
                ("expiry_date", models.CharField(max_length=7)),
                ("cvv_code", models.CharField(max_length=3)),
                ("issue_date", models.DateField()),
                ("owner_id", models.UUIDField()),
                (
                    "card_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("active", "Active"),
                            ("blocked", "Blocked"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
