# Generated by Django 4.2.3 on 2023-08-11 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("card_name", models.CharField(max_length=100)),
                ("card_number", models.CharField(max_length=16)),
                ("expiry_date", models.DateField()),
                ("cvv_code", models.CharField(max_length=4)),
                ("issue_date", models.DateField()),
                (
                    "card_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("active", "Active"),
                            ("blocked", "Blocked"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "card_frig",
                    models.CharField(
                        choices=[("unfrozen", "Provided"), ("frozen", "Frozen")],
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
