# Generated by Django 4.2.3 on 2023-07-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_frig',
            field=models.CharField(choices=[('unfrozen', 'Provided'), ('frozen', 'Frozen')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('blocked', 'Blocked')], default='new', max_length=10),
        ),
    ]
